# -*- coding: utf-8 -*-
"""Amazon-Similar-Product-Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQGY-MlFs0fb4QMwifKajSlZUG6olhWm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import zipfile
import os

import nltk
import re
nltk.download('punkt_tab')
from nltk.stem import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

zip_path = '/content/amazon_co-ecommerce_sample.csv.zip'  # Path to your ZIP file
extract_path = '/content'  # Destination folder

# Create extraction directory if not exists
os.makedirs(extract_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"Files extracted to: {extract_path}")

amazon_df = pd.read_csv('/content/amazon_co-ecommerce_sample.csv')

amazon_df.head(2)

print(amazon_df['product_information'][0])
print(amazon_df['product_description'][1])

amazon_df.columns

amazon_df.drop(columns = ['uniq_id', 'manufacturer', 'price',
                          'number_available_in_stock', 'number_of_reviews',
                          'number_of_answered_questions', 'average_review_rating',
                          'customers_who_bought_this_item_also_bought', 'product_information', 'product_description',
                          'items_customers_buy_after_viewing_this_item',
                          'customer_questions_and_answers', 'customer_reviews', 'sellers'], axis=1, inplace = True)

amazon_df.head()

amazon_df.shape

amazon_df.isnull().sum()

amazon_df.dropna(inplace = True)

amazon_df.isnull().sum()

amazon_df.shape

ps = PorterStemmer()

def tokenize_stem(text):
  # change to lower case
  text = text.lower()
  # tokenize the data word-wise
  tokens = nltk.word_tokenize(text)
  # keep only base form of words
  stemmed_tokens = [ps.stem(token) for token in tokens]
  # return words joined by space
  return " ".join(stemmed_tokens)

ps = PorterStemmer()

def tokenize_stem(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove digits and special characters except whitespace
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenize the text word-wise
    tokens = nltk.word_tokenize(text)

    # Keep only base form of words
    stemmed_tokens = [ps.stem(token) for token in tokens]

    # Return words joined by space
    return " ".join(stemmed_tokens)

amazon_df['stemmed_tokens'] = amazon_df.apply(lambda row: tokenize_stem(row['product_name'] + " " + row['amazon_category_and_sub_category'] + " " + row['description']), axis = 1)

amazon_df['stemmed_tokens'].head()

amazon_df.head()

tfidf = TfidfVectorizer()

def similarity(text1, text2):
  matrix = tfidf.fit_transform([text1, text2])
  return cosine_similarity(matrix)[0][1]

def recommend(product_name):
  stemmed_name = tokenize_stem(product_name)

  amazon_df['similarity'] = amazon_df['stemmed_tokens'].apply(lambda x: similarity(x, stemmed_name))

  result = amazon_df.sort_values(by='similarity', ascending=False).head(10)

    # Select relevant columns, including similarity
  return result[['product_name', 'amazon_category_and_sub_category', 'description', 'similarity']]

amazon_df['product_name'][5]

recommend('Marvel Select Ghost Rider Action Figure')

